### ISSUE TITLE
help ! i cant load the static files ...

### ISSUE THREAD

**Issue by zoearthmoon** [vitorfs/bootcamp#109]
when i run the first page
i found the css files is not found

i get those errors 
thanks for helper !

---------------------------------------------------------------

[05/Sep/2017 09:49:46] "GET / HTTP/1.1" 200 2421
Traceback (most recent call last):
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 392, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLPattern home ^$>], [<RegexURLPattern login ^login>], [<RegexURLPattern logout ^logout>], [<RegexURL
Pattern signup ^signup/$>], [<RegexURLPattern settings ^settings/$>], [<RegexURLPattern picture ^settings/picture/$>], [<RegexURLPattern upload_picture ^set
tings/upload_picture/$>], [<RegexURLPattern save_uploaded_picture ^settings/save_uploaded_picture/$>], [<RegexURLPattern password ^settings/password/$>], [<
RegexURLPattern network ^network/$>], [<RegexURLResolver <module 'bootcamp.feeds.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\feeds\\urls.py'> (No
ne:None) ^feeds/>], [<RegexURLResolver <module 'bootcamp.questions.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\questions\\urls.py'> (None:None) ^
questions/>], [<RegexURLResolver <module 'bootcamp.articles.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\articles\\urls.py'> (None:None) ^articles
/>], [<RegexURLResolver <module 'bootcamp.messenger.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\messenger\\urls.py'> (None:None) ^messages/>], [<
RegexURLPattern notifications ^notifications/$>], [<RegexURLPattern last_notifications ^notifications/last/$>], [<RegexURLPattern check_notifications ^notif
ications/check/$>], [<RegexURLPattern search ^search/$>], [<RegexURLPattern profile ^(?P<username>[^/]+)/$>], [<RegexURLResolver <module 'django.conf.urls.i
18n' from 'D:\\Python36-32\\lib\\site-packages\\django\\conf\\urls\\i18n.py'> (None:i18n) ^i18n/>]], 'path': 'static/css/bootcamp.css'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 109, in get_exception_response
    response = callback(request, **dict(param_dict, exception=exception))
  File "D:\Python36-32\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python36-32\lib\site-packages\django\views\defaults.py", line 45, in page_not_found
    body = template.render(context, request)
  File "D:\Python36-32\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python36-32\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' with arguments '('',)' not found. 1 pattern(s) tried: ['(?P<username>[^/]+)/$']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\Python36-32\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 53, in response_for_exception
    response = get_exception_response(request, get_resolver(get_urlconf()), 404, exc)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 119, in get_exception_response
    response = handle_uncaught_exception(request, resolver, sys.exc_info())
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "D:\Python36-32\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python36-32\lib\site-packages\django\views\defaults.py", line 74, in server_error
    return http.HttpResponseServerError(template.render())
  File "D:\Python36-32\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 392, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLPattern home ^$>], [<RegexURLPattern login ^login>], [<RegexURLPattern logout ^logout>], [<RegexURL
Pattern signup ^signup/$>], [<RegexURLPattern settings ^settings/$>], [<RegexURLPattern picture ^settings/picture/$>], [<RegexURLPattern upload_picture ^set
tings/upload_picture/$>], [<RegexURLPattern save_uploaded_picture ^settings/save_uploaded_picture/$>], [<RegexURLPattern password ^settings/password/$>], [<
RegexURLPattern network ^network/$>], [<RegexURLResolver <module 'bootcamp.feeds.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\feeds\\urls.py'> (No
ne:None) ^feeds/>], [<RegexURLResolver <module 'bootcamp.questions.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\questions\\urls.py'> (None:None) ^
questions/>], [<RegexURLResolver <module 'bootcamp.articles.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\articles\\urls.py'> (None:None) ^articles
/>], [<RegexURLResolver <module 'bootcamp.messenger.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\messenger\\urls.py'> (None:None) ^messages/>], [<
RegexURLPattern notifications ^notifications/$>], [<RegexURLPattern last_notifications ^notifications/last/$>], [<RegexURLPattern check_notifications ^notif
ications/check/$>], [<RegexURLPattern search ^search/$>], [<RegexURLPattern profile ^(?P<username>[^/]+)/$>], [<RegexURLResolver <module 'django.conf.urls.i
18n' from 'D:\\Python36-32\\lib\\site-packages\\django\\conf\\urls\\i18n.py'> (None:i18n) ^i18n/>]], 'path': 'static/js/bootcamp.js'}

During handling of the above exception, another exception occurred:

  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
Traceback (most recent call last):
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 109, in get_exception_response
    response = callback(request, **dict(param_dict, exception=exception))
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python36-32\lib\site-packages\django\views\defaults.py", line 45, in page_not_found
    body = template.render(context, request)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' with arguments '('',)' not found. 1 pattern(s) tried: ['(?P<username>[^/]+)/$']
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
Traceback (most recent call last):
  File "D:\Python36-32\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' with arguments '('',)' not found. 1 pattern(s) tried: ['(?P<username>[^/]+)/$']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python36-32\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 53, in response_for_exception
    response = get_exception_response(request, get_resolver(get_urlconf()), 404, exc)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 119, in get_exception_response
    response = handle_uncaught_exception(request, resolver, sys.exc_info())
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "D:\Python36-32\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python36-32\lib\site-packages\django\views\defaults.py", line 74, in server_error
    return http.HttpResponseServerError(template.render())
  File "D:\Python36-32\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 392, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLPattern home ^$>], [<RegexURLPattern login ^login>], [<RegexURLPattern logout ^logout>], [<RegexURL
Pattern signup ^signup/$>], [<RegexURLPattern settings ^settings/$>], [<RegexURLPattern picture ^settings/picture/$>], [<RegexURLPattern upload_picture ^set
tings/upload_picture/$>], [<RegexURLPattern save_uploaded_picture ^settings/save_uploaded_picture/$>], [<RegexURLPattern password ^settings/password/$>], [<
RegexURLPattern network ^network/$>], [<RegexURLResolver <module 'bootcamp.feeds.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\feeds\\urls.py'> (No
ne:None) ^feeds/>], [<RegexURLResolver <module 'bootcamp.questions.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\questions\\urls.py'> (None:None) ^
questions/>], [<RegexURLResolver <module 'bootcamp.articles.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\articles\\urls.py'> (None:None) ^articles
/>], [<RegexURLResolver <module 'bootcamp.messenger.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\messenger\\urls.py'> (None:None) ^messages/>], [<
RegexURLPattern notifications ^notifications/$>], [<RegexURLPattern last_notifications ^notifications/last/$>], [<RegexURLPattern check_notifications ^notif
ications/check/$>], [<RegexURLPattern search ^search/$>], [<RegexURLPattern profile ^(?P<username>[^/]+)/$>], [<RegexURLResolver <module 'django.conf.urls.i
18n' from 'D:\\Python36-32\\lib\\site-packages\\django\\conf\\urls\\i18n.py'> (None:i18n) ^i18n/>]], 'path': 'static/css/cover.css'}
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)

During handling of the above exception, another exception occurred:

  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
Traceback (most recent call last):
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 109, in get_exception_response
    response = callback(request, **dict(param_dict, exception=exception))
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\views\defaults.py", line 45, in page_not_found
    body = template.render(context, request)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python36-32\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' with arguments '('',)' not found. 1 pattern(s) tried: ['(?P<username>[^/]+)/$']
[05/Sep/2017 09:49:46] "GET /static/css/bootcamp.css?v=1 HTTP/1.1" 500 59
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
[05/Sep/2017 09:49:46] "GET /static/js/bootcamp.js HTTP/1.1" 500 59
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python36-32\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' with arguments '('',)' not found. 1 pattern(s) tried: ['(?P<username>[^/]+)/$']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python36-32\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 53, in response_for_exception
    response = get_exception_response(request, get_resolver(get_urlconf()), 404, exc)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 119, in get_exception_response
    response = handle_uncaught_exception(request, resolver, sys.exc_info())
Traceback (most recent call last):
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 392, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
  File "D:\Python36-32\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLPattern home ^$>], [<RegexURLPattern login ^login>], [<RegexURLPattern logout ^logout>], [<RegexURL
Pattern signup ^signup/$>], [<RegexURLPattern settings ^settings/$>], [<RegexURLPattern picture ^settings/picture/$>], [<RegexURLPattern upload_picture ^set
tings/upload_picture/$>], [<RegexURLPattern save_uploaded_picture ^settings/save_uploaded_picture/$>], [<RegexURLPattern password ^settings/password/$>], [<
RegexURLPattern network ^network/$>], [<RegexURLResolver <module 'bootcamp.feeds.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\feeds\\urls.py'> (No
ne:None) ^feeds/>], [<RegexURLResolver <module 'bootcamp.questions.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\questions\\urls.py'> (None:None) ^
questions/>], [<RegexURLResolver <module 'bootcamp.articles.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\articles\\urls.py'> (None:None) ^articles
/>], [<RegexURLResolver <module 'bootcamp.messenger.urls' from 'D:\\Python36-32\\works\\myvenv2\\bootcamp\\messenger\\urls.py'> (None:None) ^messages/>], [<
RegexURLPattern notifications ^notifications/$>], [<RegexURLPattern last_notifications ^notifications/last/$>], [<RegexURLPattern check_notifications ^notif
ications/check/$>], [<RegexURLPattern search ^search/$>], [<RegexURLPattern profile ^(?P<username>[^/]+)/$>], [<RegexURLResolver <module 'django.conf.urls.i
18n' from 'D:\\Python36-32\\lib\\site-packages\\django\\conf\\urls\\i18n.py'> (None:i18n) ^i18n/>]], 'path': 'static/js/ga.js'}
  File "D:\Python36-32\lib\site-packages\django\views\defaults.py", line 74, in server_error
    return http.HttpResponseServerError(template.render())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python36-32\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 109, in get_exception_response
    response = callback(request, **dict(param_dict, exception=exception))
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python36-32\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\views\defaults.py", line 45, in page_not_found
    body = template.render(context, request)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' with arguments '('',)' not found. 1 pattern(s) tried: ['(?P<username>[^/]+)/$']
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python36-32\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' with arguments '('',)' not found. 1 pattern(s) tried: ['(?P<username>[^/]+)/$']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[05/Sep/2017 09:49:46] "GET /static/css/cover.css HTTP/1.1" 500 59
  File "D:\Python36-32\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 53, in response_for_exception
    response = get_exception_response(request, get_resolver(get_urlconf()), 404, exc)
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 119, in get_exception_response
    response = handle_uncaught_exception(request, resolver, sys.exc_info())
  File "D:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "D:\Python36-32\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python36-32\lib\site-packages\django\views\defaults.py", line 74, in server_error
    return http.HttpResponseServerError(template.render())
  File "D:\Python36-32\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36-32\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python36-32\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python36-32\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' with arguments '('',)' not found. 1 pattern(s) tried: ['(?P<username>[^/]+)/$']
[05/Sep/2017 09:49:46] "GET /static/js/ga.js HTTP/1.1" 500 59

**Comment by sebastian-code** [comment]
There are two possible situations here, you are deploying to production or to development (or testing); for the first one you'll need to setup the proper software (gunicorn, nginx, caddy, apache), please refer to Django documentation on that; for the second one, remember to provide the environment variable DEBUG set to True.
