### ISSUE TITLE
issues with python manage.py migrate

### ISSUE THREAD

**Issue by akankshagr** [vitorfs/bootcamp#122]
I am in windows machine and when i run this command I am getting this issue.
 line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

My settings.ini file looks like this

[DEBUG=True]
SECRET_KEY=mys3cr3tk3y
[ALLOWED_HOSTS=*]
[DATABASE_URL=postgres://u_bootcamp:p4ssw0rd@localhost:5432/bootcamp]

please help

**Comment by sebastian-code** [comment]
Hello @akankshagr to solve your need, please refer to the project's wiki, in the [_Installing and Running Bootcamp_ section](https://github.com/vitorfs/bootcamp/wiki/Installing-and-Running-Bootcamp) you'll find the necessary instructions.

But to resume them for you, you shouldn't create a `settings.ini` file (to be honest I don't know where that came from); what you need to create is to copy the `env.example` file in the root directory to the same folder under the name `.env`, please keep the file format because the parser doesn't look for lines inside "[ ]" symbols.

**Comment by Vigor111** [comment]
I just having a issue when I run the command `python manage.py migrate`

> Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  role "u_bootcamp" does not exist

**Comment by sebastian-code** [comment]
Hi @Vigor111 The answer you're looking for is described in the last two lines, your problem is than you haven't configured the PostgreSQL server with the bootcamp database and user.

How are you deploying the PostgreSQL engine and how are you establishing connections from your Bootcamp instance to that DB engine?

**Comment by akankshagr** [comment]
In windows I can't save any file named .eve so I read through your resoved issue it says for windows use settings.ini.WHat do you mean by root folder?

**Comment by sebastian-code** [comment]
Hi @akankshagr You're actually right, sorry about that, I don't use windows, and I don't check too much about it.

Bootcamp loads the settings and elevates them to environment variables using the package `python-decouple` and you're right, that package supports a file named `settings.ini`; what I can see from your initial message is than your file is improperly configured, you're surrounding the variable lines with '[]' character, and it looks like this:
```bash
[DEBUG=True]
SECRET_KEY=mys3cr3tk3y
[ALLOWED_HOSTS=*]
[DATABASE_URL=postgres://u_bootcamp:p4ssw0rd@localhost:5432/bootcamp]```

when it should look more like this:```bash
[settings]
# PostgreSQL conf
POSTGRES_PASSWORD=mysecretpass
POSTGRES_USER=my_super_user
POSTGRES_DB=bootcamp
DATABASE_URL=postgresql://my_super_user:mysecretpass@127.0.0.1:5432/bootcamp

# Main environmental variables
DEBUG=True
SECRET_KEY=s3cr3t_key
ALLOWED_HOSTS=*
# URL to have SQLite example and to pass TravisCI
# DATABASE_URL=sqlite:////tmp/db.sqlite3```

Please check the [package documentation](https://pypi.python.org/pypi/python-decouple#id5) for a better understanding of the file format.

**Comment by sebastian-code** [comment]
Hi @akankshagr did this worked for you?

**Comment by sebastian-code** [comment]
Closing
