### ISSUE TITLE
Hai KeyError at /login 'default'

### ISSUE THREAD

**Issue by chenguanyou** [vitorfs/bootcamp#159]
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/contrib/auth/views.py", line 54, in inner
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/contrib/auth/views.py", line 150, in login
    )(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/contrib/auth/views.py", line 90, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/contrib/auth/views.py", line 119, in form_valid
    auth_login(self.request, form.get_user())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/contrib/auth/__init__.py", line 160, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.7-py3.6.egg/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/Users/zhunishengrikuaile/Downloads/bootcamp-master/bootcamp/authentication/models.py", line 206, in on_user_login
    Profile.objects.get(user=kwargs['user']).notify_login()
  File "/Users/zhunishengrikuaile/Downloads/bootcamp-master/bootcamp/authentication/models.py", line 157, in notify_login
    self.group_notification('log in')
  File "/Users/zhunishengrikuaile/Downloads/bootcamp-master/bootcamp/authentication/models.py", line 187, in group_notification
    Group('notifications').send({
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/channels/channel.py", line 65, in __init__
    self.channel_layer = channel_layers[alias]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/channels/asgi.py", line 70, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/channels/asgi.py", line 32, in make_backend
    config = self.configs[name].get("CONFIG", {})
KeyError: 'default'
How to solve it。

**Comment by sebastian-code** [comment]
I'm unable to identify with precision the issue in the error log, it appears to be something related with a constant in the settings file, I guess it is related to the REDIS configuration.

**Comment by chenguanyou** [comment]
It's been settled. Thank you very much.
