### ISSUE TITLE
Unable to use SETTINGS_MODULE=config.settings.production

### ISSUE THREAD

**Issue by dustyhorizon** [vitorfs/bootcamp#161]
Using SETTINGS_MODULE=config.settings.production throws the following error:
```
Traceback (most recent call last):
  File "/opt/bootcamp/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/bootcamp/config/settings/production.py", line 81
    'CacheControl': f'max-age={_AWS_EXPIRY}, s-maxage={_AWS_EXPIRY}, must-revalidate',
                                                                                    ^
SyntaxError: invalid syntax
```

I am trying to use the 'production' level setting for installing bootcamp but there was not a 'production' .env to reference from.

**Comment by sebastian-code** [comment]
Hello @dustyhorizon 

My first recommendation is: Go with Python 3.
Second, did you provided inside the `.env` file the required variables?

**Comment by sebastian-code** [comment]
Closing until further development.
