### ISSUE TITLE
A bug in messager app can't serialize UUID()

### ISSUE THREAD

**Issue by elshaddae** [vitorfs/bootcamp#185]
In the messager app when you try to send a message a to another user, sometimes it is not possible to submit the message-form, Error is thrown from messages/send-message/ TypeError: can't serialize UUID() in _map_channel_keys_to_connection function of channnels_redis package. I don't know Django-channels but I think it might be channels_redis core problem and not the implementation in this project.

It is hard to reproduce this bug because it happens randomly and I don't know in which conditions but I have reproduced it so many times in different settings. I don't know if it is the only one having this issue, I think if you play with messager so much you might reproduce it. Below is the full traceback.

`HTTP POST /messages/send-message/ 500 [0.11, 192.168.0.124:64502] Internal Server Error: /messages/send-message/ Traceback (most recent call last):
 File "C:\workspace\bootcamp\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner response = get_response(request)
 File "C:\workspace\bootcamp\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response response = self.process_exception_by_middleware(e, request)
 File "C:\workspace\bootcamp\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\contextlib.py", line 74, in inner return func(*args, **kwds)
 File "C:\workspace\bootcamp\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view return view_func(request, *args, **kwargs) File "C:\Users\user\workspace\bootcamp\helpers.py", line 36, in wrap return f(request, *args, **kwargs) File "C:\workspace\bootcamp\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner return func(request, *args, **kwargs) 
File "C:\Users\user\workspace\bootcamp\messager\views.py", line 89, in send_message msg = Message.send_message(sender, recipient, message)
 File "C:\Users\user\workspace\bootcamp\messager\models.py", line 94, in send_message async_to_sync(channel_layer.group_send)(recipient.username, payload)
File "C:\workspace\bootcamp\venv\lib\site-packages\asgiref\sync.py", line 64, in __call__ return call_result.result() 
File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 432, in result return self.__get_result() 
File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result raise self._exception File "C:\workspace\bootcamp\venv\lib\site-packages\asgiref\sync.py", line 78, in main_wrap result = await self.awaitable(*args, **kwargs)
File "C:\workspace\bootcamp\venv\lib\site-packages\channels_redis\core.py", line 619, in group_send channel_names, message
 File "C:\workspace\bootcamp\venv\lib\site-packages\channels_redis\core.py", line 736, in _map_channel_keys_to_connection channel_key_to_message[key] = self.serialize(channel_key_to_message[key])
 File "C:\workspace\bootcamp\venv\lib\site-packages\channels_redis\core.py", line 756, in serialize value = msgpack.packb(message, use_bin_type=True) File "C:\workspace\bootcamp\venv\lib\site-packages\msgpack\__init__.py", line 47, in packb return Packer(**kwargs).pack(o)
 File "msgpack/_packer.pyx", line 284, in msgpack._packer.Packer.pack File "msgpack/_packer.pyx", line 290, in msgpack._packer.Packer.pack 
File "msgpack/_packer.pyx", line 287, in msgpack._packer.Packer.pack
 File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack 
File "msgpack/_packer.pyx", line 281, in msgpack._packer.Packer._pack TypeError: can't serialize UUID('d30b95f9-950f-4e10-a314-e2ec32c3414c')`

I am using Redis version 3.2 and channels_redis version 2.3.2

**Comment by sebastian-code** [comment]
Can you test it using a more recent version of Redis @elshaddae ? I'm using v 4.0.

**Comment by elshaddae** [comment]
Hello @sebastian-code, I have tested the messager using Redis v 4.0 but this time I am using it on windows, it is not an official package but I still get the same error that appears randomly.

**Comment by elshaddae** [comment]
The error is caused by the payload values in the models.py of the messager app. Line number 94. There are 3 values that are not serializable, these are the message_id since it is a UUID and the remaining 2 are sender and recipient that are evaluated as SimpleLazyObject. A simple workaround is to convert these 3 variables to string just with an str() function before passing them to the payload. When I do this, everything works perfectly. I think the easier way to reproduce this bug is to have 2 devices and try to chat for a few seconds
