### ISSUE TITLE
Migration not working because of DATABASE_URL

### ISSUE THREAD

**Issue by raugbein** [vitorfs/bootcamp#188]
Hi,
I downloadet the bootcamp repo and installed all requirements. After installing postresql on local I tried to migrate, but its not working.

in **.env** I unmarked **DATABASE_URL** 
`DATABASE_URL=postgresql://bootcamp_user:bootcamp_pass@127.0.0.1:5432/bootcamp`

> (venv) sebastian@sebastian-Lenovo-G580:~/PycharmProjects/base_camp$ python manage.py makemigrations
> /home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/environ/environ.py:639: UserWarning: Error reading /home/sebastian/PycharmProjects/base_camp/.env - if you're not configuring your environment separately, check this.
>   "environment separately, check this." % env_file)
> Traceback (most recent call last):
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/environ/environ.py", line 273, in get_value
>     value = self.ENVIRON[var]
>   File "/usr/lib/python3.7/os.py", line 678, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'DATABASE_URL'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "manage.py", line 30, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
>     self.check()
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
>     include_deployment_checks=include_deployment_checks,
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
>     return checks.run_checks(**kwargs)
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
>     new_errors = check(app_configs=app_configs)
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 10, in check_url_config
>     if getattr(settings, 'ROOT_URLCONF', None):
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
>     self._setup(name)
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/sebastian/PycharmProjects/base_camp/config/settings/local.py", line 5, in <module>
>     from .base import *  # noqa
>   File "/home/sebastian/PycharmProjects/base_camp/config/settings/base.py", line 42, in <module>
>     'default': env.db('DATABASE_URL'),
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/environ/environ.py", line 204, in db_url
>     return self.db_url_config(self.get_value(var, default=default), engine=engine)
>   File "/home/sebastian/PycharmProjects/base_camp/venv/lib/python3.7/site-packages/environ/environ.py", line 277, in get_value
>     raise ImproperlyConfigured(error_msg)
> django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable

I dont changed something in the setting files. In the wiki I cant found any extra steps. what is wrong, or ehat I forgott?

Im using Ubuntu and python 3.7

**Comment by raugbein** [comment]
ahhh,I forgott the point in env
