### ISSUE TITLE
Deploy on Production failing 

### ISSUE THREAD

**Issue by bixicy** [vitorfs/bootcamp#216]
Hi.

Im trying to publish from local to production server.

with python manage.py runserver, I can run local without any error messages.

Bur when I try on production with gunicorn and NGINX compination. I cant start the server

```
(bootcamp_venv) root@h2877819:/home/websites/bootcamp# gunicorn --bind 0.0.0.0:8000 config.asgi
[2020-04-04 17:34:06 +0200] [17553] [INFO] Starting gunicorn 20.0.4
[2020-04-04 17:34:06 +0200] [17553] [INFO] Listening at: http://0.0.0.0:8000 (17553)
[2020-04-04 17:34:06 +0200] [17553] [INFO] Using worker: sync
[2020-04-04 17:34:06 +0200] [17555] [INFO] Booting worker with pid: 17555
[2020-04-04 17:34:07 +0200] [17555] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/environ/environ.py", line 273, in get_value
    value = self.ENVIRON[var]
  File "/usr/lib/python3.8/os.py", line 673, in __getitem__
    raise KeyError(key) from None
KeyError: 'DATABASE_URL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/websites/bootcamp/config/asgi.py", line 21, in <module>
    application = get_wsgi_application()
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/websites/bootcamp/config/settings/production.py", line 15, in <module>
    DATABASES['default'] = env.db('DATABASE_URL')  # noqa F405
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/environ/environ.py", line 204, in db_url
    return self.db_url_config(self.get_value(var, default=default), engine=engine)
  File "/home/websites/bootcamp/bootcamp_venv/lib/python3.8/site-packages/environ/environ.py", line 277, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable
[2020-04-04 17:34:07 +0200] [17555] [INFO] Worker exiting (pid: 17555)
[2020-04-04 17:34:07 +0200] [17553] [INFO] Shutting down: Master
[2020-04-04 17:34:07 +0200] [17553] [INFO] Reason: Worker failed to boot.
(bootcamp_venv) root@h2877819:/home/websites/bootcamp# 

```

do i have to make any extra settings for production?

**Comment by samazaphikel** [comment]
You need to install and configure some extra stuff
