### ISSUE TITLE
Database error while open messages

### ISSUE THREAD

**Issue by verkko** [vitorfs/bootcamp#226]
Here is the logs of error message

Environment:

Request Method: GET
Request URL: http://127.0.0.1:5000/messages/

Django Version: 3.0.5
Python Version: 3.7.6
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.admin',
 'django.forms',
 'crispy_forms',
 'sorl.thumbnail',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'channels',
 'django_comments',
 'graphene_django',
 'markdownx',
 'taggit',
 'bootcamp.users.apps.UsersConfig',
 'bootcamp.articles.apps.ArticlesConfig',
 'bootcamp.messager.apps.MessagerConfig',
 'bootcamp.news.apps.NewsConfig',
 'bootcamp.notifications.apps.NotificationsConfig',
 'bootcamp.qa.apps.QaConfig',
 'bootcamp.search.apps.SearchConfig',
 'debug_toolbar',
 'django_extensions']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']

Traceback (most recent call last):
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ameen\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Users\ameen\PycharmProjects\bk5\bootcamp\bootcamp\messager\views.py", line 38, in get_queryset
    active_user = Message.objects.get_most_recent_conversation(self.request.user)
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\ameen\PycharmProjects\bk5\bootcamp\bootcamp\messager\models.py", line 28, in get_most_recent_conversation
    qs = qs_sent.union(qs_recieved).latest("timestamp")
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\db\models\query.py", line 660, in latest
    return self.reverse()._earliest(*fields)
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\db\models\query.py", line 654, in _earliest
    return obj.get()
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\db\models\query.py", line 411, in get
    num = len(clone)
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\db\models\sql\compiler.py", line 1138, in execute_sql
    sql, params = self.as_sql()
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\db\models\sql\compiler.py", line 499, in as_sql
    result, params = self.get_combinator_sql(combinator, self.query.combinator_all)
  File "C:\Users\ameen\PycharmProjects\bk5\bkvenv\lib\site-packages\django\db\models\sql\compiler.py", line 436, in get_combinator_sql
    raise DatabaseError('ORDER BY not allowed in subqueries of compound statements.')

Exception Type: DatabaseError at /messages/
Exception Value: ORDER BY not allowed in subqueries of compound statements.

**Comment by verkko** [comment]
changed database to mysql working fine..
