### ISSUE TITLE
Getting decouple error while starting up site

### ISSUE THREAD

**Issue by isht3** [vitorfs/bootcamp#71]
When I try to run the site I get a
`decouple.UndefinedValueError: ALLOWED_HOSTS option not found and default value was not defined.` 

I can't seem to figure out where I'm going wrong. Any thoughts?

full error:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/appu/bootcamp/bootcamp/settings.py", line 22, in <module>
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
  File "/usr/local/lib/python2.7/dist-packages/decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/decouple.py", line 77, in __call__
    return self.get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/decouple.py", line 64, in get
    raise UndefinedValueError('%s option not found and default value was not defined.' % option)
decouple.UndefinedValueError: ALLOWED_HOSTS option not found and default value was not defined.

```

**Comment by isht3** [comment]
Seems like the python-mysql client was not working properly with Python-3, I fixed it by changing into mysql.

**Comment by geandersonlenz** [comment]
I have the same error in python 3, I have fixed with .env but didn't work. Could you solve this issue?

**Comment by sebastian-code** [comment]
Hi @geandersonlenz If you are having issues with the `ALLOWED_HOST` variable, then the thing you have to do is to declare it. But to be more helpful, do you mind to share the _traceback_ of your error?
