### ISSUE TITLE
when run 'python manage.py migrate',show 'if engine is none else engine'

### ISSUE THREAD

**Issue by OLDFE** [vitorfs/bootcamp#78]
Traceback (most recent call last):
  File "D:/Document/VirtualWS/bootcamp-master/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\PengFan\virtualEnv\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "D:\PengFan\virtualEnv\lib\site-packages\django\core\management\__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "D:\PengFan\virtualEnv\lib\site-packages\django\conf\__init__.py", line 53, in __getattr__
    self._setup(name)
  File "D:\PengFan\virtualEnv\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "D:\PengFan\virtualEnv\lib\site-packages\django\conf\__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "d:\program files\python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\Document\VirtualWS\bootcamp-master\bootcamp\settings.py", line 17, in <module>
    default=config('DATABASE_URL')
  File "D:\PengFan\virtualEnv\lib\site-packages\dj_database_url.py", line 51, in config
    config = parse(s, engine, conn_max_age)
  File "D:\PengFan\virtualEnv\lib\site-packages\dj_database_url.py", line 103, in parse
    engine = SCHEMES[url.scheme] if engine is None else engine
KeyError: ''

**Comment by JeeveshN** [comment]
@OLDFE in settings.py make these changes and make sure that your .env file is in the folder named 'bootcamp' which is a subfolder not the main one.
```python
try:
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
except:
    pass
```

**Comment by 1500256797** [comment]
`D:\blog>python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\conf\__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\blog\bootcamp\settings.py", line 17, in <module>
    default=config('DATABASE_URL')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\dj_database_url.py", line 54, in config
    config = parse(s, engine, conn_max_age)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\dj_database_url.py", line 111, in parse
    engine = SCHEMES[url.scheme] if engine is None else engine
KeyError: ''
`
