### ISSUE TITLE
Unable to syncdb 

### ISSUE THREAD

**Issue by ChillarAnand** [vitorfs/bootcamp#8]
Cloned the repo and when I run 
        python manage.py syncdb 

I am getting this error 
decouple.UndefinedValueError: SECRET_KEY option not found and default value was not defined.

**Comment by lydemo** [comment]
I do create a configured env. file at root file and run python manage.py syncdb,but still appear the error:
decouple.UndefinedValueError: SECRET_KEY option not found and default value was not defined. I can't 
figure out why...

**Comment by vitorfs** [comment]
@lydemo what operating system are you using? OS X, Linux, Windows...? 
Is the file named `env` or `.env`? (note the dot in the beginning)
Do you have a `SECRET_KEY` property defined in the `.env` file?

**Comment by lydemo** [comment]
@vitorfs Yeah I did...I just learn django, and I also suspect there is something wrong with the secret key, I used the generator to generate one, a 50-bit one, is it right?

**Comment by lydemo** [comment]
@vitorfs I installed it on win7 or win10, the same error appeared...

**Comment by vitorfs** [comment]
Since you are using Windows, instead of using a `.env` file you should use `settings.ini`
You can read more in the official documentation of `python-decouple` for instructions about Windows setup:

https://pypi.python.org/pypi/python-decouple

I have also wrote an article about the `python-decouple` package, it might also be useful:

http://simpleisbetterthancomplex.com/2015/11/26/package-of-the-week-python-decouple.html

**Comment by lydemo** [comment]
@vitorfs  Well, it works...but transferred to database configuration error...I will get across it, and thank you for reminding me of that

**Comment by lydemo** [comment]
@vitorfs Hey buddie I will bother you again...I set the DATABASE_URL just like 'mysql://root:1234@localhost:3306/ly/db.opt', then run the python manage.py syncdb, then appear a new error: ImproperlyConfigured: settings.DATABASE is improperly configured. I wonder whether I leave something important, such as configurations in setting.py of bootcamp. Is it right?

**Comment by vitorfs** [comment]
The configuration string is incorrect, the `dj_database_url` expects the MySQL connection string in the following format:

    mysql://USER:PASSWORD@HOST:PORT/NAME

So, in this case you should put it this way:

    DATABASE_URL=mysql://root:1234@localhost:3306

https://github.com/kennethreitz/dj-database-url

**Comment by SaurabhMishra4894** [comment]
it can be a text file..? bcoz the file is asking for a name . Its not accepting just .env

**Comment by Javvadhi** [comment]
HI iam getting the below  error 
decouple.UndefinedValueError: ALLOWED_HOSTS option not found and default value was not defined.

**Comment by arichar1990** [comment]
@Javvadhi I am having the same issue. It says to Declare it as envvar or define a default value, but I am not sure what that means.

**Comment by arichar1990** [comment]
@Javvadhi I got past it, by adding ALLOWED_HOSTS = 'localhost' to the .env file.

**Comment by ranjan-swd** [comment]
> The configuration string is incorrect, the `dj_database_url` expects the MySQL connection string in the following format:
> 
> ```
> mysql://USER:PASSWORD@HOST:PORT/NAME
> ```
> So, in this case you should put it this way:
> 
> ```
> DATABASE_URL=mysql://root:1234@localhost:3306/ly
> ```
> In case `ly` is actually the name of your database
> 
> https://github.com/kennethreitz/dj-database-url

its not working .....
i have used like ...
DATABASE_URL=mysql://root:root@localhost:3306/thuraya_db
but getting errors like ...
C:\Users\User\AppData\Local\Programs\Python\Python37\python.exe C:/Users/User/Desktop/DjangoPROJECT/bloodhound-master/bloodhound-master/manage.py
Traceback (most recent call last):
  File "C:/Users/User/Desktop/DjangoPROJECT/bloodhound-master/bloodhound-master/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\django\conf\__init__.py", line 48, in __getattr__
    self._setup(name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\django\conf\__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\django\conf\__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\User\Desktop\DjangoPROJECT\bloodhound-master\bloodhound-master\bloodhound\settings.py", line 77, in <module>
    default = config('mysql://root:root@localhost:3306/thurata_db')
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple.py", line 198, in __call__
    return self.config(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple.py", line 77, in __call__
    return self.get(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple.py", line 64, in get
    raise UndefinedValueError('%s option not found and default value was not defined.' % option)
decouple.UndefinedValueError: mysql://root:root@localhost:3306/thurata_db option not found and default value was not defined.
