### ISSUE TITLE
What is this error when I try create a new account??

### ISSUE THREAD

**Issue by richardsonsamuel** [vitorfs/bootcamp#85]
```
Environment:


Request Method: POST
Request URL: http://localhost:8000/signup/

Django Version: 1.10.4
Python Version: 3.5.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'bootcamp.activities',
 'bootcamp.articles',
 'bootcamp.authentication',
 'bootcamp.core',
 'bootcamp.feeds',
 'bootcamp.messenger',
 'bootcamp.questions',
 'bootcamp.search')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')



Traceback:

File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

The above exception (relation "auth_user" does not exist
LINE 1: SELECT (1) AS "a" FROM "auth_user" WHERE UPPER("auth_user"."...
                               ^
) was the direct cause of the following exception:

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/bootcamp/bootcamp/authentication/views.py" in signup
  12.         if not form.is_valid():

File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py" in is_valid
  169.         return self.is_bound and not self.errors

File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py" in errors
  161.             self.full_clean()

File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py" in full_clean
  370.         self._clean_fields()

File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py" in _clean_fields
  388.                     value = field.clean(value)

File "/usr/local/lib/python3.5/site-packages/django/forms/fields.py" in clean
  160.         self.run_validators(value)

File "/usr/local/lib/python3.5/site-packages/django/forms/fields.py" in run_validators
  143.                 v(value)

File "/bootcamp/bootcamp/authentication/forms.py" in UniqueUsernameIgnoreCaseValidator
  51.     if User.objects.filter(username__iexact=value).exists():

File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py" in exists
  660.             return self.query.has_results(using=self.db)

File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/query.py" in has_results
  494.         return compiler.has_results()

File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py" in has_results
  806.         return bool(self.execute_sql(SINGLE))

File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py" in execute_sql
  835.             cursor.execute(sql, params)

File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py" in execute
  79.             return super(CursorDebugWrapper, self).execute(sql, params)

File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.5/site-packages/django/db/utils.py" in __exit__
  94.                 six.reraise(dj_exc_type, dj_exc_value, traceback)

File "/usr/local/lib/python3.5/site-packages/django/utils/six.py" in reraise
  685.             raise value.with_traceback(tb)

File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /signup/
Exception Value: relation "auth_user" does not exist
LINE 1: SELECT (1) AS "a" FROM "auth_user" WHERE UPPER("auth_user"."...
                               ^

```

**Comment by sebastian-code** [comment]
Hi @richardsonsamuel it looks like you haven't applied the migrations. Con you confirm on that?

**Comment by richardsonsamuel** [comment]
@sebastian-code Hi, These are the commands I executed on the docker container to migrate the DB, but still getting same error.

```
$ docker exec src_django_1 python manage.py migrate
Operations to perform:
  Apply all migrations: activities, articles, auth, authentication, contenttypes, feeds, messenger, questions, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

$ docker exec src_django_1 python manage.py  makemigrations
Migrations for 'activities':
  bootcamp/activities/migrations/0002_auto_20170522_2302.py:
    - Alter field activity_type on activity
    - Alter field notification_type on notification
Migrations for 'articles':
  bootcamp/articles/migrations/0002_auto_20170522_2302.py:
    - Alter field status on article

$ docker exec src_django_1 python manage.py migrate
Operations to perform:
  Apply all migrations: activities, articles, auth, authentication, contenttypes, feeds, messenger, questions, sessions
Running migrations:
  Applying activities.0002_auto_20170522_2302... OK
  Applying articles.0002_auto_20170522_2302... OK
```

**Comment by richardsonsamuel** [comment]
Actually correction the issue seems to be once I've applied the migrations and try to start up the containers...

```
$ docker-compose up
Creating src_postgres_1
Creating src_django_1
Attaching to src_postgres_1, src_django_1
django_1    | Performing system checks...
django_1    | 
django_1    | System check identified no issues (0 silenced).
postgres_1  | FATAL:  the database system is starting up
postgres_1  | LOG:  database system was shut down at 2017-05-22 23:33:36 UTC
django_1    | Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f3690bb81e0>
django_1    | Traceback (most recent call last):
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
django_1    |     self.connect()
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
django_1    |     self.connection = self.get_new_connection(conn_params)
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
django_1    |     connection = Database.connect(**conn_params)
django_1    |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
django_1    |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
django_1    | psycopg2.OperationalError: FATAL:  the database system is starting up
django_1    | 
django_1    | 
django_1    | The above exception was the direct cause of the following exception:
django_1    | 
django_1    | Traceback (most recent call last):
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
django_1    |     fn(*args, **kwargs)
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
django_1    |     self.check_migrations()
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 437, in check_migrations
django_1    |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
django_1    |     self.loader = MigrationLoader(self.connection)
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
django_1    |     self.build_graph()
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 203, in build_graph
django_1    |     self.applied_migrations = recorder.applied_migrations()
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
django_1    |     self.ensure_schema()
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
django_1    |     if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 231, in cursor
django_1    |     cursor = self.make_debug_cursor(self._cursor())
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 204, in _cursor
django_1    |     self.ensure_connection()
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
django_1    |     self.connect()
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
django_1    |     six.reraise(dj_exc_type, dj_exc_value, traceback)
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
django_1    |     raise value.with_traceback(tb)
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
django_1    |     self.connect()
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
django_1    |     self.connection = self.get_new_connection(conn_params)
django_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
django_1    |     connection = Database.connect(**conn_params)
django_1    |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
django_1    |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
django_1    | django.db.utils.OperationalError: FATAL:  the database system is starting up
django_1    | 
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
```

**Comment by sebastian-code** [comment]
Hi @richardsonsamuel checking the logs, I have three questions:

1. With what porpoise are you currently trying to launch the project? To test it in a more development/testing oriented environment o directly aimed to deploy it into a production scenario?
2. Have you configured your docker-compose environment variables?
3. Did you configured your `.env` file with the _PostgreSQL_ address properly configured using the URL format?

The docker-compose recipe is oriented to a development scenario; is actually possible to migrate it to production with little effort, but you need to configure your variables properly.
